
exports.TOKEN = 'NzAxNDI5NDUyNzA5NjkxNDQz.Xpxawg.aW2iTlrtFMv9iOIeHDDbZnlW_sE'; //THIS BOT IS FOR MULTIPLE GUILD
exports.PREFIX = 'm!';

exports.GOOGLE_API_KEY = 'AIzaSyADR83u3IjYzcgEHyBApnTBF6K3kNLKkFc';
